# Copyright (c) 2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

'left_hip_pitch_joint': 0
'left_hip_roll_joint': 1
'left_hip_yaw_joint': 2
'left_knee_joint': 3
'left_ankle_roll_joint': 4
'left_ankle_pitch_joint': 5
'right_hip_pitch_joint': 6
'right_hip_roll_joint': 7
'right_hip_yaw_joint': 8
'right_knee_joint': 9
'right_ankle_roll_joint': 10
'right_ankle_pitch_joint': 11
'waist_yaw_joint': 12
'waist_roll_joint': 13
'waist_pitch_joint': 14
'head_pitch_joint': 15
'head_yaw_joint': 16
'left_shoulder_pitch_joint': 17
'left_shoulder_roll_joint': 18
'left_shoulder_yaw_joint': 19
'left_elbow_joint': 20
'left_wrist_roll_joint': 21
'left_wrist_pitch_joint': 22
'left_wrist_yaw_joint': 23
'right_shoulder_pitch_joint': 24
'right_shoulder_roll_joint': 25
'right_shoulder_yaw_joint': 26
'right_elbow_joint': 27
'right_wrist_roll_joint': 28
'right_wrist_pitch_joint': 29
'right_wrist_yaw_joint': 30
'left_thumb_CMC_FE': 31
'left_thumb_CMC_AA': 32
'left_thumb_MCP_FE': 33
'left_thumb_MCP_AA': 34
'left_thumb_IP': 35
'left_index_MCP_FE': 36
'left_index_MCP_AA': 37
'left_index_PIP': 38
'left_index_DIP': 39
'left_middle_MCP_FE': 40
'left_middle_MCP_AA': 41
'left_middle_PIP': 42
'left_middle_DIP': 43
'left_ring_MCP_FE': 44
'left_ring_MCP_AA': 45
'left_ring_PIP': 46
'left_ring_DIP': 47
'left_pinky_CMC': 48
'left_pinky_MCP_FE': 49
'left_pinky_MCP_AA': 50
'left_pinky_PIP': 51
'left_pinky_DIP': 52
'right_thumb_CMC_FE': 53
'right_thumb_CMC_AA': 54
'right_thumb_MCP_FE': 55
'right_thumb_MCP_AA': 56
'right_thumb_IP': 57
'right_index_MCP_FE': 58
'right_index_MCP_AA': 59
'right_index_PIP': 60
'right_index_DIP': 61
'right_middle_MCP_FE': 62
'right_middle_MCP_AA': 63
'right_middle_PIP': 64
'right_middle_DIP': 65
'right_ring_MCP_FE': 66
'right_ring_MCP_AA': 67
'right_ring_PIP': 68
'right_ring_DIP': 69
'right_pinky_CMC': 70
'right_pinky_MCP_FE': 71
'right_pinky_MCP_AA': 72
'right_pinky_PIP': 73
'right_pinky_DIP': 74
